export const CHARACTER_PHOTO_MAX_EDGE = 1024;
export const CHARACTER_PHOTO_JPEG_QUALITY = 88;

export const FILM_POSTER_MAX_WIDTH = 1080;
export const FILM_POSTER_MAX_HEIGHT = 1620;
export const FILM_POSTER_JPEG_QUALITY = 90;

export const BLURRED_PLACEHOLDER_IMAGE_QUALITY = 65;
