import type { UserFilm } from "@/lib/film-creation/types";
import {
  buildLegacyLocalizedFilmTitle,
  buildLocalizedFilmTitle,
  FILM_STYLE_IDS,
} from "@/lib/i18n/film-labels";
import type { LocaleCode } from "@/lib/i18n/locales";
import { createTranslator } from "@/lib/i18n/translator";

function isAutoGeneratedFilmTitle(film: UserFilm): boolean {
  const locales: LocaleCode[] = ["fr", "en"];
  return locales.some((locale) => {
    if (film.title === buildLocalizedFilmTitle(film.themes, locale)) {
      return true;
    }
    return FILM_STYLE_IDS.some(
      (style) =>
        film.title === buildLegacyLocalizedFilmTitle(style, film.themes, locale)
    );
  });
}

function stripSynopsisPrefix(text: string): string {
  return text
    .replace(/^Résumé\s*:\s*/i, "")
    .replace(/^Summary\s*:\s*/i, "")
    .trim();
}

export function getFilmDisplayTitle(
  film: UserFilm,
  userLocale: LocaleCode,
  generatedTitle?: string | null
): string {
  if (isAutoGeneratedFilmTitle(film)) {
    return buildLocalizedFilmTitle(film.themes, userLocale);
  }

  if (generatedTitle?.trim()) {
    return generatedTitle.trim();
  }

  return film.title;
}

export function buildUserFilmPageCopy(
  film: UserFilm,
  userLocale: LocaleCode,
  resume: string | null,
  tagline: string | null
) {
  const t = createTranslator(userLocale);

  const synopsisSource =
    resume?.trim() ||
    film.additionalInfo?.trim() ||
    t("space.filmSynopsisFallback");
  const synopsis = stripSynopsisPrefix(synopsisSource);

  const displayTagline =
    tagline?.trim() || film.tagline?.trim() || undefined;

  return {
    tagline: displayTagline,
    synopsisHeading: t("space.filmSynopsisHeading"),
    synopsis,
  };
}
