import type { UserFilm } from "@/lib/film-creation/types";
import { isUserFreeTrialFilm } from "@/lib/film-creation/is-free-trial-film";
import { isUserSampleFilm } from "@/lib/film-creation/is-sample-film";
import type { StoryGenerationStatus } from "@/lib/story-generation/types";
import {
  buildLegacyLocalizedFilmTitle,
  buildLocalizedFilmTitle,
  FILM_STYLE_IDS,
  normalizeFilmTheme,
  type FilmThemeId,
} from "@/lib/i18n/film-labels";
import type { LocaleCode } from "@/lib/i18n/locales";
import { createTranslator } from "@/lib/i18n/translator";
import type { TranslationKey } from "@/lib/i18n/translator";

function isAutoGeneratedFilmTitle(film: UserFilm): boolean {
  const locales: LocaleCode[] = ["fr", "en"];
  return locales.some((locale) => {
    if (film.title === buildLocalizedFilmTitle(film.themes, locale)) {
      return true;
    }
    return FILM_STYLE_IDS.some(
      (style) =>
        film.title === buildLegacyLocalizedFilmTitle(style, film.themes, locale)
    );
  });
}

function stripSynopsisPrefix(text: string): string {
  return text
    .replace(/^Résumé\s*:\s*/i, "")
    .replace(/^Summary\s*:\s*/i, "")
    .trim();
}

function getMainCharacter(film: UserFilm) {
  return film.characters.find((c) => c.isMain) ?? film.characters[0] ?? null;
}

function themeIntroKey(theme: FilmThemeId): TranslationKey {
  return `space.filmThemeIntro.${theme}` as TranslationKey;
}

export function formatFilmSynopsisText(text: string): string {
  return stripSynopsisPrefix(text);
}

export function getFilmDisplayTitle(
  film: UserFilm,
  userLocale: LocaleCode,
  generatedTitle?: string | null
): string {
  if (isUserFreeTrialFilm(film)) {
    return buildLocalizedFilmTitle(film.themes, userLocale);
  }

  if (isUserSampleFilm(film)) {
    if (generatedTitle?.trim()) {
      return generatedTitle.trim();
    }
    return buildLocalizedFilmTitle(film.themes, userLocale);
  }

  if (generatedTitle?.trim()) {
    return generatedTitle.trim();
  }

  if (isAutoGeneratedFilmTitle(film)) {
    return buildLocalizedFilmTitle(film.themes, userLocale);
  }

  return film.title;
}

export function buildUserFilmPageCopy(
  film: UserFilm,
  userLocale: LocaleCode,
  resume: string | null,
  tagline: string | null,
  storyStatus?: StoryGenerationStatus
) {
  const t = createTranslator(userLocale);

  const main = getMainCharacter(film);
  const heroName = main?.prenom ?? t("space.filmHeroFallbackName");
  const primaryTheme = film.themes
    .map((theme) => normalizeFilmTheme(String(theme)))
    .find((theme): theme is FilmThemeId => theme != null);

  const intro = primaryTheme
    ? t(themeIntroKey(primaryTheme), { name: heroName })
    : t("space.filmIntro", { name: heroName });

  if (isUserFreeTrialFilm(film)) {
    const synopsis = `${t("space.filmSynopsisHeading")} ${t("space.freeTrialFilmSynopsisFallback")}`;

    return {
      tagline: t("space.freeTrialFilmTagline"),
      intro,
      lead: t("space.filmLead", { name: heroName }),
      heroName,
      heroPhotoSrc: main?.photoSrc,
      heroPhotoAlt: t("space.filmHeroPhotoAlt", { name: heroName }),
      synopsis,
    };
  }

  if (isUserSampleFilm(film)) {
    const displayTagline =
      tagline?.trim() || film.tagline?.trim() || t("space.sampleFilmTagline");

    if (resume?.trim()) {
      const synopsisBody = stripSynopsisPrefix(resume.trim());
      return {
        tagline: displayTagline,
        intro,
        lead: t("space.filmLead", { name: heroName }),
        heroName,
        heroPhotoSrc: main?.photoSrc,
        heroPhotoAlt: t("space.filmHeroPhotoAlt", { name: heroName }),
        synopsis: `${t("space.filmSynopsisHeading")} ${synopsisBody}`,
      };
    }

    const pendingSynopsis =
      storyStatus === "generating"
        ? t("space.storyStatusGenerating")
        : storyStatus === "failed"
          ? t("space.storyStatusFailed")
          : t("space.sampleFilmSynopsisPending");

    return {
      tagline: displayTagline,
      intro,
      lead: t("space.filmLead", { name: heroName }),
      heroName,
      heroPhotoSrc: main?.photoSrc,
      heroPhotoAlt: t("space.filmHeroPhotoAlt", { name: heroName }),
      synopsis: `${t("space.filmSynopsisHeading")} ${pendingSynopsis}`,
    };
  }

  const synopsisBody = stripSynopsisPrefix(
    resume?.trim() || film.additionalInfo?.trim() || t("space.filmSynopsisFallback")
  );
  const synopsis = `${t("space.filmSynopsisHeading")} ${synopsisBody}`;

  const displayTagline =
    tagline?.trim() || film.tagline?.trim() || undefined;

  return {
    tagline: displayTagline,
    intro,
    lead: t("space.filmLead", { name: heroName }),
    heroName,
    heroPhotoSrc: main?.photoSrc,
    heroPhotoAlt: t("space.filmHeroPhotoAlt", { name: heroName }),
    synopsis,
  };
}
